module.exports = {

    breakpoints: {
        'sm': '576px',
        'md': '768px',
        'lg': '992px',
        'xl': '1200px'
    },

    rules: {
        w: 'width',
        h: 'height',
        maw: 'max-width',
        mah: 'max-height',
        miw: 'min-width',
        mih: 'min-height',
        po: 'position',
        fl: 'float',
        cl: 'clear',
        d: 'display',
        t: 'top',
        b: 'bottom',
        l: 'left',
        r: 'right',
        o: 'opacity',
        cus: 'cursor',

        ovf: 'overflow',
        ovfx: 'overflow-x',
        ovfy: 'overflow-y',
        ovfw: 'overflow-wrap',

        p: 'padding',
        pl: 'padding-left',
        pr: 'padding-right',
        pt: 'padding-top',
        pb: 'padding-bottom',

        m: 'margin',
        ml: 'margin-left',
        mr: 'margin-right',
        mt: 'margin-top',
        mb: 'margin-bottom',

        co: 'color',
        fo: 'font',
        fost: 'font-style',
        fov: 'font-variant',
        fow: 'font-weight',
        fosz: 'font-size',
        fof: 'font-family ',
        lh: 'line-height',
        lb: 'line-break',

        txta: 'text-align',
        txti: 'text-indent',
        txtj: 'text-justify',
        txtor: 'text-orientation',
        txtov: 'text-overflow',
        txtr: 'text-rendering',
        txtt: 'text-transform',
        txte: 'text-emphasis',
        txtec: 'text-emphasis-color',
        txtep: 'text-emphasis-position',
        txtes: 'text-emphasis-style',
        txtd: 'text-decoration',
        txtdc: 'text-decoration-color',
        txtdl: 'text-decoration-line',
        txtdw: 'text-decoration-style',

        jc: 'justify-content',
        ac: 'align-content',
        ji: 'justify-items',
        js: 'justify-self',
        pi: 'place-items',
        pc: 'place-content',
        g: 'gap',
        cg: 'column-gap',
        gg: 'grid-gap',
        rg: 'row-gap',
        ord: 'order',
        flx: 'flex',
        flxb: 'flex-basis',
        flxd: 'flex-direction',
        flxf: 'flex-flow',
        flxg: 'flex-grow',
        flxd: 'flex-shrink',
        flxw: 'flex-wrap',

        bg: 'background',
        bgcl: 'background-clip',
        bgco: 'background-color',
        bgi: 'background-image',
        bgo: 'background-origin',
        bgp: 'background-position',
        bgpx: 'background-position-x',
        bgpy: 'background-position-y',
        bgr: 'background-repeat',
        bgs: 'background-size',

        out: 'outline',
        outc: 'outline-color',
        outs: 'outline-style',
        outw: 'outline-width',
        outo: 'outline-offset',

        bo: 'border',
        bos: 'border-style',
        bow: 'border-width',
        boc: 'border-color',
        bora: 'border-radius',

        bob: 'border-bottom',
        bobs: 'border-bottom-style',
        bobw: 'border-bottom-width',
        bobc: 'border-bottom-color',
        boblr: 'border-bottom-left-radius',
        bobrr: 'border-bottom-right-radius',

        bot: 'border-top',
        bots: 'border-top-style',
        botw: 'border-top-width',
        botc: 'border-top-color',
        botlr: 'border-top-left-radius',
        botrr: 'border-top-right-radius',

        bor: 'border-right',
        bors: 'border-right-style',
        borw: 'border-right-width',
        borc: 'border-right-color',
        borlr: 'border-right-left-radius',
        borrr: 'border-right-right-radius',

        bol: 'border-left',
        bols: 'border-left-style',
        bolw: 'border-left-width',
        bolc: 'border-left-color',
        bollr: 'border-left-left-radius',
        bolrr: 'border-left-right-radius',
    }
}
